@url = http://localhost:5083/api/appointment

### Create an appointment ###

POST {{url}}
Content-Type: application/json

{
  "slotId": "f6fd0552-6449-4e52-9113-0398e3a2d32e",
  "patientId": "7f671378-f0d2-46a1-bb2e-750b64b2d9f5"
}

### Get all appointments ###

GET {{url}}

### Get appointment by ID ###

GET {{url}}/ba5c2b37-46bc-4788-b171-e0748d9ed847

### Get Doctor Appointments ###

GET {{url}}/doctor/3556301e-2993-4dfd-8259-701c2e8dd1e9

### Update an appointment ###

PUT {{url}}/e020e5d7-79a7-4b32-b31e-9e652a8a2001
Content-Type: application/json

{
  "status": "Completed"
}

### Delete an appointment ###

DELETE {{url}}/{appointmentId}
