@url = http://localhost:5083/api/appointment

### Create an appointment ###

POST {{url}}
Content-Type: application/json

{
  "slotId": "427482de-c901-4a82-9908-b32ccef331b3",
  "patientId": "86365262-62af-44f0-9e00-f5d6cdabac66"
}

### Get all appointments ###

GET {{url}}

### Get appointment by ID ###

GET {{url}}/ba5c2b37-46bc-4788-b171-e0748d9ed847

### Get Doctor Appointments ###

GET {{url}}/doctor/c5021196-ffba-4bf6-917a-61a6702c16e6

### Update an appointment ###

PUT {{url}}/04017947-62c1-420d-a4a9-2c64f65b3722
Content-Type: application/json

{
  "status": "Completed"
}

### Delete an appointment ###

DELETE {{url}}/{appointmentId}
