###
### DoctorController API Requests
###

@url = http://localhost:5083/api/doctor

# Add a new doctor
POST {{url}}
Content-Type: application/json

{
  "name": "Dr. John Woe"
}

###

# Check if doctor with specific ID exists
GET {{url}}/exists/f5b7c72e-4eea-4ef3-aff8-f48ab4cbb1d3

###

# Retrieve a doctor by ID
GET {{url}}/f5b7c72e-4eea-4ef3-aff8-f48ab4cbb1d3

###

# Retrieve all doctors
GET {{url}}

###

# Update an existing doctor
PUT {{url}}/3556301e-2993-4dfd-8259-701c2e8dd1e9
Content-Type: application/json

{
  "name": "Dr. Jane Smith"
}

###

# Delete a doctor by ID
DELETE {{url}}/f5b7c72e-4eea-4ef3-aff8-f48ab4cbb1d3
