###
### PatientController API Requests
###

@url = http://localhost:5083/api/patient

###
### Get all patients
###

GET {{url}}

###
### Add new patient
###

POST {{url}}
Content-Type: application/json

{
  "name": "John Qoe"
}

###
### Check if patient exists
###

GET {{url}}/exists/e2766cc0-a83a-4eaf-881c-533240c8882e

###
### Get patient by ID
###

GET {{url}}/e2766cc0-a83a-4eaf-881c-533240c8882e

###
### Update patient
###

PUT {{url}}/7f671378-f0d2-46a1-bb2e-750b64b2d9f5
Content-Type: application/json

{
  "name": "John Smith"
}

###
### Delete patient
###

DELETE {{url}}/e2766cc0-a83a-4eaf-881c-533240c8882e
