###
### PatientController API Requests
###

@url = http://localhost:5083/api/patient

###
### Get all patients
###

GET {{url}}

###
### Add new patient
###

POST {{url}}
Content-Type: application/json

{
  "name": "John Doe"
}

###
### Check if patient exists
###

GET {{url}}/exists/4b0a2f88-de9f-4200-9cb3-a04bb70d1f74

###
### Get patient by ID
###

GET {{url}}/4b0a2f88-de9f-4200-9cb3-a04bb70d1f74

###
### Update patient
###

PUT {{url}}/86365262-62af-44f0-9e00-f5d6cdabac66
Content-Type: application/json

{
  "id": "86365262-62af-44f0-9e00-f5d6cdabac66",
  "name": "John Smith"
}

###
### Delete patient
###

DELETE {{url}}/3540e4f8-2d77-40b9-bd28-9f38d2b7f6cd
