###
### TimeSlotController API Requests
###

@url = http://localhost:5083/api/timeslot

### Get Time Slot by ID ###
GET {{url}}/6c7f905f-fe2f-4c85-81b5-1de09c12b2aa
Content-Type: application/json

### Get All Time Slots ##
GET {{url}}

### Get All Available Time Slots ###
GET {{url}}/available

### Get Time Slots by Doctor ID ###
GET {{url}}/doctors/c5021196-ffba-4bf6-917a-61a6702c16e6

### Get Available Time Slots by Doctor ID ###
GET {{url}}/doctors/c5021196-ffba-4bf6-917a-61a6702c16e6/available

### Get Reserved Time Slots by Doctor ID ###
GET {{url}}/doctors/c5021196-ffba-4bf6-917a-61a6702c16e6/reserved

### Add Time Slot for Doctor ###
POST {{url}}/doctors/c5021196-ffba-4bf6-917a-61a6702c16e6/add
Content-Type: application/json

{
  "time": "21/06/2023 11:00 AM",
  "cost": 5.00
}

### Update Time Slot ##
PUT {{url}}/63f27b86-81b3-4241-a0d2-6ab46d36253f
Content-Type: application/json

{
  "isReserved": true
}

### Delete Time Slot ###
DELETE {{url}}/6c7f905f-fe2f-4c85-81b5-1de09c12b2aa
