###
### TimeSlotController API Requests
###

@url = http://localhost:5083

### Get Time Slot by ID ###
GET {{url}}/api/timeslots/6c7f905f-fe2f-4c85-81b5-1de09c12b2aa
Content-Type: application/json

### Get Time Slots by Doctor ID ###
GET {{url}}/api/timeslots/doctors/c5021196-ffba-4bf6-917a-61a6702c16e6

### Add Time Slot for Doctor ###
POST {{url}}/api/timeslots/doctors/c5021196-ffba-4bf6-917a-61a6702c16e6/add
Content-Type: application/json

{
  "dateTimeString": "21/06/2023 10:00 AM",
  "cost": 10.00
}

### Delete Time Slot ###
DELETE {{url}}/api/timeslots/6c7f905f-fe2f-4c85-81b5-1de09c12b2aa
