services:

  PostgreSQL:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: appointments_db
    ports:
      - 5434:5432